name = "youtube-transcript-mcp"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "TRANSCRIPT_CACHE"
id = "a31420fc7cbc43e79960d8f1fce6dc68"

# Remove any durable_objects configuration
# Remove any environment variables related to GitHub OAuth

[vars]
# Add any environment variables here if needed